from machine import Pin
import time
led1 = Pin(25, Pin.OUT)
Verde = Pin(11, Pin.OUT)
Amarillo = Pin(14, Pin.OUT)
Rojo = Pin(15, Pin.OUT)
Prueba = Pin(0, Pin.OUT) 

led1.on()
Verde.on()
Amarillo.on()
Rojo.on()
time.sleep(3)
Verde.off()
Amarillo.off()
Rojo.off()
Prueba.on()
while True:
    Verde.on()
    time.sleep(3)
    Verde.off()
    Amarillo.on()
    time.sleep(0.5)
    Amarillo.off()
    time.sleep(0.5)
    Amarillo.on()
    time.sleep(0.5)
    Amarillo.off()
    time.sleep(0.5)
    Amarillo.on()
    time.sleep(0.5)
    Amarillo.off()
    Rojo.on()
    time.sleep(3)
    Rojo.off()
